[theme]
primaryColor = "#0ea5e9"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1e293b"
font = "sans serif"

[server]
port = 8501
address = "127.0.0.1"
headless = true
enableCORS = false
baseUrlPath = ""
enableXsrfProtection = false

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false
